name = "phantom-mail-admin"
main = "worker.js"
compatibility_date = "2024-01-01"

[vars]
MODE = "hosted"
RESEND_QUOTA_LIMIT = "3000"
ADMIN_REPORT_EMAIL = "admin@mail.unknowns.app"
RESEND_API_KEY = "re_YOUR_KEY_HERE"
ADMIN_PASSWORD = "PhantomAdmin2026!"

[[kv_namespaces]]
binding = "EMAILS"
id = "e939b6b99b65475f921642edf71d0187"

[[kv_namespaces]]
binding = "INBOX_META"
id = "73a3e881eda34256bd01216bd9d79bcc"

[[kv_namespaces]]
binding = "API_KEYS"
id = "5aa53de9a1ee4e3d942807f9330997c8"

[[r2_buckets]]
binding = "ATTACHMENTS"
bucket_name = "phantom-attachments"

[triggers]
crons = ["0 8 1 * *"] # Automated monthly report on 1st of every month at 08:00 UTC
